/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SicsAlgorithams_AdjListMat_Bidirected {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SicsAlgorithams_AdjListMat_Bidirected(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SicsAlgorithams_AdjListMat_Bidirected obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sicsSWIGJNI.delete_SicsAlgorithams_AdjListMat_Bidirected(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SicsAlgorithams_AdjListMat_Bidirected(int num_g, int num_h) {
    this(sicsSWIGJNI.new_SicsAlgorithams_AdjListMat_Bidirected(num_g, num_h), true);
  }

  public void set_vertex_label_graph_1(int v, String c) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_set_vertex_label_graph_1(swigCPtr, this, v, c);
  }

  public void add_edge_graph_1(int v1, int v2) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_add_edge_graph_1(swigCPtr, this, v1, v2);
  }

  public void set_vertex_label_graph_2(int v, String c) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_set_vertex_label_graph_2(swigCPtr, this, v, c);
  }

  public void add_edge_graph_2(int v1, int v2) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_add_edge_graph_2(swigCPtr, this, v1, v2);
  }

  public void backjumping_bitset_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backjumping_bitset_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void backjumping_bitset_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backjumping_bitset_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void backjumping_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backjumping_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void backjumping_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backjumping_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void backjumping_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backjumping_ind(swigCPtr, this, v_order);
  }

  public void backtracking_adjacentconsistency_forwardcount_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_forwardcount_ind(swigCPtr, this, v_order);
  }

  public void backtracking_adjacentconsistency_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_ind(swigCPtr, this, v_order);
  }

  public void backtracking_adjacentconsistency_precount_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_precount_ind(swigCPtr, this, v_order);
  }

  public void backtracking_bitset_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_bitset_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void backtracking_bitset_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_bitset_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void backtracking_degreeprune_adjacentconsistency_forwardcount_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_forwardcount_ind(swigCPtr, this, v_order);
  }

  public void backtracking_degreeprune_adjacentconsistency_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_ind(swigCPtr, this, v_order);
  }

  public void backtracking_degreeprune_adjacentconsistency_precount_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_precount_ind(swigCPtr, this, v_order);
  }

  public void backtracking_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void backtracking_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void backtracking_forwardcount_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_forwardcount_ind(swigCPtr, this, v_order);
  }

  public void backtracking_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_backtracking_ind(swigCPtr, this, v_order);
  }

  public void conflictbackjumping_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void conflictbackjumping_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void conflictbackjumping_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreeprune_ac1_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_ac1_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreeprune_countingalldifferent_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_countingalldifferent_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreesequenceprune_ac1_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_ac1_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreesequenceprune_countingalldifferent_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_countingalldifferent_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_bitset_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void forwardchecking_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_low_bitset_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_bitset_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_low_bitset_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_bitset_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_low_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_low_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardchecking_low_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardcheckingbackjumping_low_bitset_degreeprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardcheckingbackjumping_low_bitset_degreeprune_ind(swigCPtr, this, v_order);
  }

  public void lazyforwardcheckingbackjumping_low_bitset_degreesequenceprune_ind(String v_order) {
    sicsSWIGJNI.SicsAlgorithams_AdjListMat_Bidirected_lazyforwardcheckingbackjumping_low_bitset_degreesequenceprune_ind(swigCPtr, this, v_order);
  }

}
