/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sicsSWIGJNI {
  public final static native long new_SicsAlgorithams_AdjListMat_Bidirected(int jarg1, int jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_set_vertex_label_graph_1(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, int jarg2, String jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_add_edge_graph_1(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, int jarg2, int jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_set_vertex_label_graph_2(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, int jarg2, String jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_add_edge_graph_2(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, int jarg2, int jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backjumping_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backjumping_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backjumping_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backjumping_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backjumping_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_adjacentconsistency_precount_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_adjacentconsistency_precount_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_backtracking_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_conflictbackjumping_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_ac1_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_countingalldifferent_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_ac1_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_countingalldifferent_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_forwardchecking_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardchecking_low_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardcheckingbackjumping_low_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Bidirected_lazyforwardcheckingbackjumping_low_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Bidirected jarg1_, String jarg2);
  public final static native void delete_SicsAlgorithams_AdjListMat_Bidirected(long jarg1);
  public final static native long new_SicsAlgorithams_AdjListMat_Undirected(int jarg1, int jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_set_vertex_label_graph_1(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, int jarg2, String jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_add_edge_graph_1(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, int jarg2, int jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_set_vertex_label_graph_2(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, int jarg2, String jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_add_edge_graph_2(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, int jarg2, int jarg3);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backjumping_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backjumping_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backjumping_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backjumping_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backjumping_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_adjacentconsistency_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_adjacentconsistency_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_adjacentconsistency_precount_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_degreeprune_adjacentconsistency_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_degreeprune_adjacentconsistency_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_degreeprune_adjacentconsistency_precount_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_forwardcount_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_backtracking_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_conflictbackjumping_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_conflictbackjumping_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_conflictbackjumping_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreeprune_ac1_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreeprune_countingalldifferent_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreesequenceprune_ac1_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreesequenceprune_countingalldifferent_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_forwardchecking_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_low_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_low_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_low_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_low_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardchecking_low_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardcheckingbackjumping_low_bitset_degreeprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void SicsAlgorithams_AdjListMat_Undirected_lazyforwardcheckingbackjumping_low_bitset_degreesequenceprune_ind(long jarg1, SicsAlgorithams_AdjListMat_Undirected jarg1_, String jarg2);
  public final static native void delete_SicsAlgorithams_AdjListMat_Undirected(long jarg1);
}
